Dilas feat
glocurrency/polaris-bank-api-client-php pull request #1
Opened 2023-02-20 08:56 UTC by chedilas

2023-02-20 12:36 UTC, brokeyourbike commented
- use `"phpunit/phpunit": "^9",`
- please add `.devcontainer` similar to the one used in https://github.com/glocurrency/access-bank-service
- make the version in composer "0.0.1" instead of "1.0.0"

2023-02-24 10:33 UTC, chedilas commented
@brokeyourbike Can we agree on a day for the review please

2023-02-24 12:33 UTC, brokeyourbike requested changes
Please take a look at my comments

2023-02-24 12:33 UTC, brokeyourbike commented on src/Client.php
> +    }
No need for this method

2023-02-24 12:33 UTC, brokeyourbike commented on src/Clientback.php
> +<?php
This file should be removed if it's not used

2023-02-24 12:33 UTC, brokeyourbike commented on src/Client.php
> +        // $responseBody = json_decode($response->getBody(), true);
remove the dead code

2023-02-24 12:33 UTC, brokeyourbike commented on src/Client.php
> +    public function sendDomesticTransaction(BankTransactionInterface $bankTransaction): TransactionResponse
please add the doc block to all methods with the link to the polaris API documentation like we agreed
example:

```suggestion
    /** @link link-to-the-api-method-documentation */
    public function sendDomesticTransaction(BankTransactionInterface $bankTransaction): TransactionResponse
```

2023-02-24 12:33 UTC, brokeyourbike commented on src/Client.php
> +    public function fetchDomesticTransactionStatusRaw(BankTransactionInterface $bankTransaction): TransactionResponse
1. it looks like `sendDomesticTransaction` and `fetchDomesticTransactionStatusRaw` doing the same thing
2. add the @link

2023-02-24 12:33 UTC, brokeyourbike commented on src/Client.php
> +    public function fetchDomesticBankAccountNameRaw(string $requestRef, string $accountNumber): ResponseInterface
1. please use the `performRequest` when making request and return the typed response like you did with other methods
2. add the @link

2023-02-24 12:33 UTC, brokeyourbike commented on src/Client.php
> +    }
there is no need for this method

2023-02-24 12:33 UTC, brokeyourbike commented on src/Client.php
> +    }
there is no need for this method, adjust the `performRequest` to suit your needs

2023-02-24 12:33 UTC, brokeyourbike commented on src/Client.php
> +    }
please resolve other threads, and we can discuss how to apply best practice for this method as well, as it's not clear for me if it's required for all API requests or just for specific one

2023-02-24 12:33 UTC, brokeyourbike commented on src/Client.php
> +    public function FetchAuthTokenRaw(): FetchAuthTokenResponse
1. method should start with lowercase
2. add the @link

2023-02-24 12:33 UTC, brokeyourbike commented on src/Client.php
> +    }
there is no need for this method, API client just performs requests, and decodes response, any judgement about where it was successful or not should be done in the polaris-bank-service

2023-02-24 12:33 UTC, brokeyourbike commented on src/Enums/ErrorCodeEdnum.php
> +enum ErrorCodeEnum: string
1. I can see this error codes are just a copy from the AccessBank, adjust them for PolarisBank or remove the file if you are not sure what to put here right now
2. this will probably be the values of the `data.provider_response_code`

2023-02-24 12:33 UTC, brokeyourbike commented on src/Factories/HttpClientFactory.php
> +<?php
there is no need for this file, please remove it

2023-02-24 12:33 UTC, brokeyourbike commented on src/Models/FetchAccountBalanceResponse.php
> +    }
there is no need for `__construct` or `fromJson` methods, remove them

2023-02-24 12:33 UTC, brokeyourbike commented on src/Interfaces/ConfigInterface.php
> +    public function getCacheTtl();
`getCacheTtl` should have a return type as other methods

2023-02-24 12:33 UTC, brokeyourbike commented on src/Models/FetchBankAccountNameResponse.php
> +    }
I think there is no need for this methods, and if "fetch bank account" method is **not required for sending transaction** you can remove the method and response from implementation to reduce complexity and focus on what is important

2023-02-24 12:33 UTC, brokeyourbike commented on tests/FetchAccountBalanceRawTest.php
> +    public function testFromJson()
1. it's not exactly the test we are looking for
2. if "fetch account balance" method is not required to send transaction, I suggest you to remove it and related files to focus on the most important parts

2023-02-24 12:33 UTC, brokeyourbike commented on tests/FetchAuthTokenRawTest.php
> +        $api->setHttpClient($mockClient); // set the mockClient instance
there is no need to use `setHttpClient`, you just passed the client on the line above

2023-02-24 12:33 UTC, brokeyourbike commented on tests/FetchDomesticBankAccountNameRawTest.php
> +class FetchBankAccountNameResponseTest extends TestCase
1. this is not the tests we are looking for
2. remove files related to this method if it's not required as I stated previously

2023-02-24 12:33 UTC, brokeyourbike commented on src/Enums/ErrorCodeEdnum.php
> +<?php
you have typo in the file name `ErrorCodeEdnum`

2023-02-24 12:33 UTC, brokeyourbike commented on tests/SendDomesticTransactionTest.php
> +            }');
is this response related to the PolarisBank in any way?

2023-02-24 12:38 UTC, chedilas commented on tests/FetchDomesticBankAccountNameRawTest.php
> +class FetchBankAccountNameResponseTest extends TestCase
Okay I will remove them, right away but what is done there is the same as for getting the status for the transactions.

2023-02-24 12:48 UTC, chedilas commented on tests/FetchAuthTokenRawTest.php
> +        $api->setHttpClient($mockClient); // set the mockClient instance
I tried that but it was flagging an error, so i had to make a fix, mean while i will take a further look into it and fix that accordingly to match what is required.

2023-02-24 12:49 UTC, chedilas commented on tests/FetchAccountBalanceRawTest.php
> +    public function testFromJson()
Okay Noted

2023-02-24 12:50 UTC, chedilas commented on .github/workflows/static.yml
> +    branches: [ dilas-feat ]
Alright noted, I will do so

2023-02-24 12:51 UTC, chedilas commented on composer.json
> +        "php": "*",
This will be corrected

2023-02-24 12:51 UTC, chedilas commented on src/Client.php
> +    private string $reference;
I think this was an oversite, it will be removed

2023-02-24 12:53 UTC, chedilas commented on src/Client.php
> +    protected $client;
This will be looked up on, I think there was a reason why i used $client, i can't remembered what happened, never the less, I will look at to resolve all the comments made.

2023-02-24 12:54 UTC, chedilas commented on src/Enums/ErrorCodeEdnum.php
> +<?php
Okay I will correct them ASAP

2023-02-27 11:56 UTC, chedilas commented on composer.json
> +        ],
removed, this was an over site during setting up the project

2023-02-27 11:57 UTC, chedilas commented on composer.json
> +        "php": "*",
I have resolved this too

2023-02-27 11:59 UTC, chedilas commented on src/Client.php
> +    private string $reference;
I can't remember why i used that, but I have resolved it by removing it

2023-02-27 12:46 UTC, chedilas commented on tests/FetchDomesticBankAccountNameRawTest.php
> +class FetchBankAccountNameResponseTest extends TestCase
This method have been removed.

2023-02-27 12:46 UTC, chedilas commented on src/Enums/ErrorCodeEdnum.php
> +<?php
resolved

2023-02-27 12:47 UTC, chedilas commented on tests/SendDomesticTransactionTest.php
> +            }');
resolved this with the appropriate mockedresponse

2023-02-28 00:32 UTC, chedilas commented on src/Models/FetchAccountBalanceResponse.php
> +    }
This is done with intend that the class  carries a JSON response from the expected specific structure with  the following properties: status, message, and data. So that If the JSON response has a different structure it will not work. that is why i had to write a constructor method that accepts: $status, $message, and $data. The reason is for the arguments to initialize the corresponding properties of the object and also setup a static method to call fromJson to accepts a JSON string as an argument.

2023-02-28 00:34 UTC, chedilas commented on src/Interfaces/ConfigInterface.php
> +    public function getCacheTtl();
there is no point using this again, so i removed it.

2023-02-28 00:35 UTC, chedilas commented on src/Models/FetchBankAccountNameResponse.php
> +    }
resolved

2023-02-28 00:35 UTC, chedilas commented on src/Clientback.php
> +<?php
This has been removed already

2023-02-28 00:38 UTC, chedilas commented on src/Client.php
> +    }
resolved

2023-02-28 08:55 UTC, chedilas commented on src/Client.php
> +    }
resolved

2023-02-28 08:55 UTC, chedilas commented on src/Client.php
> +    public function FetchAuthTokenRaw(): FetchAuthTokenResponse
resolved

2023-02-28 11:15 UTC, brokeyourbike commented on src/Models/FetchAccountBalanceResponse.php
> +    }
There is no need to do this, please follow the DTO approach with setting just the properties on the class like this 
https://github.com/brokeyourbike/access-bank-api-client-php/blob/main/src/Models/FetchAccountBalanceResponse.php . If the response will not have the required fields, API client will throw or will set null depending on how you described them.

2023-02-28 11:16 UTC, brokeyourbike commented on src/Models/FetchAccountBalanceResponse.php
> +    }
moreover, there is no need to get the balance in the first place, so you can remove this file as well as the method

2023-02-28 11:18 UTC, brokeyourbike commented on src/Client.php
> +    }
$cache should not be null

2023-02-28 11:38 UTC, chedilas commented on src/Models/FetchAccountBalanceResponse.php
> +    }
okay no problem

2023-02-28 19:33 UTC, chedilas commented on tests/SendDomesticTransactionTest.php
> +            }');
Resolved this already

2023-02-28 19:40 UTC, chedilas commented on tests/FetchAuthTokenRawTest.php
> +        $api->setHttpClient($mockClient); // set the mockClient instance
resolved

2023-02-28 19:41 UTC, chedilas commented on tests/FetchAccountBalanceRawTest.php
> +    public function testFromJson()
resolved

2023-02-28 19:43 UTC, chedilas commented on src/Client.php
> +    protected $client;
resolved

2023-02-28 19:43 UTC, chedilas commented on src/Client.php
> +    private string $reference;
resolved

2023-03-02 14:02 UTC, brokeyourbike commented on .github/workflows/static.yml
> +    branches: [ dilas-feat ]
remove `static.yml` as well if you removed the `phpstan.neon`

2023-03-02 14:05 UTC, brokeyourbike commented on src/Client.php
> +                'Signature' => $this->config->getSignature()
the signature cannot come from the config, you need to add the logic here to generate it, I suggest you to pass the `$reference` directly to the method and use it to generate the signature, as it's probably required for all requests

2023-03-02 14:08 UTC, brokeyourbike commented on src/Client.php
> +    public function authTokenCacheKey(): string
you don't need authTokenCacheKey, FetchAuthTokenRaw, getAuthToken and all related files, polaris useing different authentication flow, is this correct? if not, please describe the flow used for auth here

2023-03-04 12:49 UTC, brokeyourbike commented on src/Client.php
> +use Psr\SimpleCache\CacheInterface;
not required anymore

2023-03-04 12:50 UTC, brokeyourbike commented on src/Client.php
> +use Glocurrency\PolarisBank\Models\FetchAuthTokenResponse;
those imports are redundant

2023-03-04 12:50 UTC, brokeyourbike commented on src/Client.php
> +    private int $ttlMarginInSeconds = 60;
`$ttlMarginInSeconds` is not required anymore

2023-03-04 12:52 UTC, brokeyourbike commented on tests/Disbursment.php
> +<?php
1. make sure the filename is the same as the class `DisbursmentTest`
2. is there any value in this test, what is the difference between the `SendTransactionTest`

2023-03-04 12:52 UTC, brokeyourbike commented on tests/SendTransactionTest.php
> +class sendTransactionTest extends TestCase
class name should not be lowercase

2023-03-04 12:53 UTC, brokeyourbike commented on tests/SendTransactionTest.php
> +            ->getMock();
looks like this is unused

2023-03-04 12:53 UTC, brokeyourbike commented on tests/SendTransactionTest.php
> +            ->getMock();
looks like this is unused as well

2023-03-04 12:54 UTC, brokeyourbike commented on tests/ClientTest.php
> +        $mockedCache = $this->getMockBuilder(\Psr\SimpleCache\CacheInterface::class)->getMock();
you don't use the cache anymore

2023-03-10 08:54 UTC, closed without merging